services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - planner

volumes:
  postgres_data:

networks:
  planner:
